name: Check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Gp
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.4"
      - name: Install dependencies
        run: go get -v -t -d ./...
      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
      - name: Test
        run: go test ./...
